backend/urls.py
# -*- coding: utf-8 -*-
#!/usr/bin/env python
#
# Copyright (c) 2010-2014 Mariusz Smenzyk <mariusz.smenzyk@sizeof.pl>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
"""

@author: Mariusz Smenzyk
@license: MIT License
@contact: mariusz.smenzyk@sizeof.pl
"""
from django.conf.urls import *
from rebateceo.urls import urlpatterns as rebateceo_urls


# Custom urls
urlpatterns = patterns('',
    # ...
) + rebateceo_urls

rebateceo/contrib/api/urls.py
# -*- coding: utf-8 -*-
#!/usr/bin/env python
#
# Copyright (c) 2010-2014 Mariusz Smenzyk <mariusz.smenzyk@sizeof.pl>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
"""

@author: Mariusz Smenzyk
@license: MIT License
@contact: mariusz.smenzyk@sizeof.pl
"""
from django.conf.urls import patterns, url, include
from . import views


urlpatterns = patterns('',
    #  Generic
    url(r'^content-type/list/', views.ContentTypeListView.as_view(), name='contenttype-list'),
    url(r'^info/', views.InfoView.as_view(), name='info'),
    url(r'^ping/', views.PingView.as_view(), name='ping'),
    url(r'^code/list/', views.CodeListView.as_view(), name='code-list'),

    #  Endpoints
    url(r'^map/', include('rebateceo.contrib.map.api.urls', namespace='map')),
    url(r'^tags/', include('rebateceo.contrib.tags.api.urls', namespace='tags')),
    url(r'^shop/', include('rebateceo.contrib.shop.api.urls', namespace='shop')),
    url(r'^trans/', include('rebateceo.contrib.trans.api.urls', namespace='trans')),
    url(r'^stand/', include('rebateceo.contrib.stand.api.urls', namespace='stand')),
    url(r'^nameday/', include('rebateceo.contrib.nameday.api.urls', namespace='nameday')),
    url(r'^mall/', include('rebateceo.contrib.mall.api.urls', namespace='mall')),
    url(r'^advert/', include('rebateceo.contrib.advert.api.urls', namespace='advert')),
    url(r'^contest/', include('rebateceo.contrib.contest.api.urls', namespace='contest')),
    url(r'^contest/bonarka1/', include('rebateceo.contrib.bonarka1.api.urls', namespace='bonarka1')),
    url(r'^backup/', include('rebateceo.contrib.backup.api.urls', namespace='backup')),
    url(r'^news/', include('rebateceo.contrib.news.api.urls', namespace='news')),
    url(r'^promotion/', include('rebateceo.contrib.promotion.api.urls', namespace='promotion')),
    url(r'^purchase/', include('rebateceo.contrib.purchase.api.urls', namespace='purchase')),
    url(r'^receipt/', include('rebateceo.contrib.purchase.api.urls', namespace='receipt')),  # alias
    url(r'^rebate/', include('rebateceo.contrib.rebate.api.urls', namespace='rebate')),
    url(r'^bookmark/', include('rebateceo.contrib.bookmark.api.urls', namespace='bookmark')),
    url(r'^profile/', include('rebateceo.contrib.profile.api.urls', namespace='profile')),
    url(r'^screensaver/', include('rebateceo.contrib.screensaver.api.urls', namespace='screensaver')),
    url(r'^tracking/', include('rebateceo.contrib.tracking.api.urls', namespace='tracking')),
    url(r'^campaign/', include('rebateceo.contrib.campaign.api.urls', namespace='campaign')),
    url(r'^card/', include('rebateceo.contrib.card.api.urls', namespace='card')),
    url(r'^verifier/', include('rebateceo.contrib.verifier.api.urls', namespace='verifier')),
    url(r'^loyalty/', include('rebateceo.contrib.loyalty.api.urls', namespace='loyalty')),
    url(r'^cache/', include('rebateceo.contrib.cache.api.urls', namespace='cache')),

    # url(r'^selfkiosk/', include('rebateceo.contrib.selfkiosk.api.urls', namespace='selfkiosk')),
    # url(r'^lottery/', include('rebateceo.contrib.lottery.api.urls', namespace='lottery')),
    # url(r'^lottery-v2/', include('rebateceo.contrib.lottery_v2.api.urls', namespace='lottery-v2')),
    # url(r'^lottery-v3/', include('rebateceo.contrib.lottery_v3.api.urls', namespace='lottery-v3')),
    # url(r'^lottery-v4/', include('rebateceo.contrib.lottery_v4.api.urls', namespace='lottery-v4')),
    # url(r'^printlog/', include('rebateceo.contrib.printlog.api.urls', namespace='printlog')),
    # url(r'^adv/', include('rebateceo.contrib.adv.api.urls', namespace='adv')),

    # url(r'^backup/', BackupView.as_view(), name='backup'),
)

rebateceo/contrib/map/urls.py
# -*- coding: utf-8 -*-
#!/usr/bin/env python
#
# Copyright (c) 2010-2014 Mariusz Smenzyk <mariusz.smenzyk@sizeof.pl>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
"""

@author: Mariusz Smenzyk
@license: MIT License
@contact: mariusz.smenzyk@sizeof.pl
"""
from django.conf.urls import patterns, url
from .views import MapEditorView


urlpatterns = patterns('',
    url(r'editor/', MapEditorView.as_view(), name='editor'),
)

rebateceo/contrib/rebate/urls.py
from django.conf.urls import patterns, url

from .views import RebateListView, RebateCreateView, RebateDeleteView, RebateUpdateView

urlpatterns = patterns('',
                       url(r'^list/$', RebateListView.as_view(), name='list'),
                       url(r'^create/$', RebateCreateView.as_view(), name='create'),
                       url(r'^update/(?P<pk>[0-9]+)/$', RebateUpdateView.as_view(), name='update'),
                       url(r'^delete/(?P<pk>[0-9]+)/$', RebateDeleteView.as_view(), name='delete'),
)

rebateceo/urls.py
# -*- coding: utf-8 -*-
#!/usr/bin/env python
#
# Copyright (c) 2010-2014 Mariusz Smenzyk <mariusz.smenzyk@sizeof.pl>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
"""

@author: Mariusz Smenzyk
@license: MIT License
@contact: mariusz.smenzyk@sizeof.pl
"""
from django.conf.urls import *
from django.conf import settings
from django.contrib import admin

admin.autodiscover()


urlpatterns = patterns('',
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^tinymce/', include('tinymce.urls')),

    # Project urls
    # url(r'^map/', include('rebateceo.contrib.map.urls', namespace='map')),
    # url(r'^demo/', include('rebateceo.contrib.demo.urls')),
    # url(r'^manager/', include('rebateceo.contrib.manager.urls', namespace='manager')),
    # url(r'^operator/', include('rebateceo.contrib.operator.urls', namespace='operator')),
    # url(r'^account/', include('rebateceo.contrib.account.urls')),
    # url(r'^rebate/', include('rebateceo.contrib.rebate.urls', namespace='rebate')),

    # url(r'^shops/', include('rebateceo.contrib.shop.urls', namespace='shop')),
    # url(r'^sms/', include('rebateceo.contrib.sms.urls', namespace='sms')),
    # url(r'^report/', include('rebateceo.contrib.report.urls', namespace='report')),
    # url(r'^purchase/', include('rebateceo.contrib.purchase.urls', namespace='purchase')),
    # url(r'^receipt/', include('rebateceo.contrib.receipt.urls', namespace='receipt')),
    # url(r'^campaigns/', include('rebateceo.contrib.campaigns.urls', namespace='campaigns')),
    # url(r'^qrcode/', include('rebateceo.contrib.urls', namespace='qrcode')),
    url(r'^tags/', include('rebateceo.contrib.tags.urls', namespace='tags')),
    url(r'^websocket/', include('rebateceo.contrib.websocket.urls', namespace='websocket')),
    url(r'^tracking/', include('rebateceo.contrib.tracking.urls', namespace='tracking')),
    url(r'^account/', include('userena.urls')),
    url(r'^messages/', include('userena.contrib.umessages.urls')),
    url(r'^api/', include('rebateceo.contrib.api.urls', namespace='api')),
    url(r'^api/auth/', include('rebateceo.contrib.authorize.api.urls', namespace='auth')),
    url(r'^api/docs/', include('rest_framework_swagger.urls')),
    url(r'^crossdomain.xml$', 'rebateceo.crossdomain.xml', name='crossdomain'),
    url(r'^$', include('rebateceo.contrib.dashboard.urls', namespace='dashboard')),
    url(r'^cache/', include('rebateceo.contrib.cache.urls', namespace='cache')),
    url(r'^promotions/', include('rebateceo.contrib.promotion.urls', namespace='promotions')),
    )


if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve',
         {'document_root': settings.MEDIA_ROOT}),
        (r'^static/(?P<path>.*)$', 'django.views.static.serve',
         {'document_root': settings.STATIC_ROOT}),
    )

rebateceo/contrib/advert/models.py
# -*- coding: utf-8 -*-
#!/usr/bin/env python
#
# Copyright (c) 2010-2014 Mariusz Smenzyk <mariusz.smenzyk@sizeof.pl>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
"""

@author: Mariusz Smenzyk
@license: MIT License
@contact: mariusz.smenzyk@sizeof.pl
"""

import uuid
import reversion
from actstream import registry
from decimal import Decimal
from datetime import datetime
from django.db import models
from django.db.models import Q
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth import get_user_model as user_model
from rebateceo.utils.dates import format_date, granular_now


def upload_to(instance, filename):
    return '/'.join(['banners', str(filename)])


class SectionManager(models.Manager):
    pass


class Section(models.Model):
    title = models.CharField(_('title'), max_length=255)
    slug = models.SlugField(max_length=255)
    objects = SectionManager()

    def __unicode__(self):
        return self.title

    class Meta:
        verbose_name = u"Section"
        verbose_name_plural = u"Sections"
        ordering = ('pk', )


class BannerManager(models.Manager):
    def active(self):
        date_filter = Q(publication_date__lte=granular_now) & (
        Q(publication_end_date__isnull=True) | Q(publication_end_date__gt=granular_now))
        queryset = self.filter(date_filter, active=True)
        return queryset


class Banner(models.Model):
    TARGETS = (
        ('rabatomat', _('rabatomat')),
        ('mobile', _('mobile')),
        ('verifier', _('verifier')),
        ('website', _('website')),
    )
    section = models.ForeignKey(Section, blank=True, null=True)
    title = models.CharField(_('title'), max_length=255)
    slug = models.SlugField(max_length=255)
    image = models.FileField(max_length=255, upload_to=upload_to)
    target = models.CharField(max_length=16, choices=TARGETS, default='rabatomat')
    active = models.BooleanField(default=False)
    publication_date = models.DateTimeField(_('publication date'), default=granular_now)
    publication_end_date = models.DateTimeField(_('publication end date'), blank=True, null=True,
                                                help_text=_('Leave empty if the entry should stay active forever.'))

    objects = BannerManager()

    def __unicode__(self):
        return str(self.title)

    class Meta:
        verbose_name = u"Banner"
        verbose_name_plural = u"Banners"
        ordering = ('target', 'pk', )

    @property
    def image_link(self):
        return '<a href="%s" target="_blank"><img src="%s"></a>' % (self.image.url, self.image.url)

    def save(self, *args, **kwargs):
        if self.publication_date:
            self.publication_date = granular_now(self.publication_date)
        if self.publication_end_date:
            self.publication_end_date = granular_now(self.publication_end_date)
        super(Banner, self).save(*args, **kwargs)

    def admin_image(self):
        return self.image_link
    admin_image.allow_tags = True
    admin_image.short_description = _('image')

    def admin_datepublisher(self):
        return u'%s &ndash; %s' % (
            format_date(self.publication_date),
            format_date(self.publication_end_date, '&infin;'),
        )
    admin_datepublisher.allow_tags = True
    admin_datepublisher.short_description = _('visible from-to')


reversion.register(Section)
reversion.register(Banner)

rebateceo/contrib/backup/api/models.py
# Create your models here.

rebateceo/contrib/backup/models.py
# Create your models here.

rebateceo/contrib/campaign/api/models.py
# Create your models here.

rebateceo/contrib/card/old/api/models.py
# Create your models here.

rebateceo/contrib/dashboard/models.py
# Create your models here.

rebateceo/contrib/loyalty/api/models.py
# Create your models here.

rebateceo/templates/rebate/base.html
{% extends "base.html" %}

 {% block page-header-title %}
    Rebates
{% endblock %}

rebateceo/templates/rebate/create.html
{% extends "rebate/update.html" %}
{% load bootstrap3 %}

 {% block page-header-title %}
    Dodaj nowy rabat
{% endblock %}

rebateceo/templates/rebate/delete.html
{% extends "rebate/base.html" %}

{% block content %}
    <div class="row">
        <div class="col-md-12">

            <h2>Czy jesteś pewny, że chcesz usunąć ten rekord?</h2>
            <form class="form-horizontal" role="form" method="post" action="">
                {% csrf_token %}
                <div class="form-actions fluid">
                    <div class="col-md-offset-3 col-md-9">
                        <button type="submit" class="btn red">Usuń</button>
                        <a href="{% url 'rebate:list' %}" class="btn default">Anuluj</a>
                    </div>
                </div>
            </form>

        </div>
    </div>
{% endblock %}

rebateceo/templates/rebate/list.html
{% extends "rebate/base.html" %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN SAMPLE TABLE PORTLET-->
            <div class="portlet">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-gift"></i>Rebates list
                    </div>
                    <div class="tools">
                        <a href="javascript:;" class="collapse">
                        </a>
                        <!--<a href="#portlet-config" data-toggle="modal" class="config">-->
                        <!--</a>-->
                        <!--<a href="javascript:;" class="reload">-->
                        <!--</a>-->
                        <!--<a href="javascript:;" class="remove">-->
                        <!--</a>-->
                    </div>
                </div>
                <div class="portlet-body">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered table-advance table-hover">
                        <thead>
                        <tr>
                            <th>
                                Image
                            </th>
                            <th class="hidden-xs">
                                Shop
                            </th>
                            <th>
                                Content
                            </th>
                            <th>
                                Program
                            </th>
                            <th>
                                Type
                            </th>
                            <th>
                                Segment
                            </th>
                            <th>
                                Media group
                            </th>
                            <th>
                                Actions
                            </th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for rebate in object_list %}
                            <tr>
                                <!--<td class="highlight">-->
                                    <!--<div class="success">-->
                                    <!--</div>-->
                                    <!--<a href="{% url 'rebate:update' rebate.pk %}">-->
                                    <!--{{ rebate.program }}</a>-->
                                <!--</td>-->
                                <td class="hidden-xs" width="150">
                                    {% if rebate.image %}
                                        <img src="{{ rebate.image.url }}" width="150" />
                                    {% else %}
                                        -
                                    {% endif %}
                                </td>
                                <td class="hidden-xs">
                                     {{ rebate.shop }}
                                </td>
                                <td class="hidden-xs">
                                     {{ rebate.content }}
                                </td>
                                <td class="hidden-xs">
                                     {{ rebate.type.title|default:'-' }}
                                </td>
                                <td class="hidden-xs">
                                     {{ rebate.type.title|default:'-' }}
                                </td>
                                <td class="hidden-xs">
                                     {{ rebate.segment|default:'-' }}
                                </td>

                                <td class="hidden-xs">
                                    {% for group in rebate.groups.all %}
                                        <div>{{ group.title }}</div>
                                    {% empty %}
                                        All
                                    {% endfor %}
                                </td>
                                <td>
                                    <a href="{% url 'admin:rebate_rebate_change' rebate.pk %}" class="btn default btn-xs purple"><i class="fa fa-edit"></i> Edit </a>
                                    <a href="{% url 'admin:rebate_rebate_delete' rebate.pk %}" class="btn default btn-xs black"> <i class="fa fa-trash-o"></i> Delete </a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <!-- END SAMPLE TABLE PORTLET-->
        </div>
    </div>
{% endblock %}

rebateceo/templates/rebate/update.html
{% extends "rebate/base.html" %}
{% load bootstrap3 %}

 {% block page-header-title %}
    Edycja rabatu <i>{{ object }}</i>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">

            <form class="" role="form" method="post" action="">
                {% csrf_token %}
                <div class="form-body">
                    {% bootstrap_form form %}
                </div>
                <div class="form-actions fluid">
                    <div class="col-md-offset-3 col-md-9">
                        <button type="submit" class="btn red">Zapisz</button>
                        <a href="{% url 'rebate:list' %}" class="btn default">Anuluj</a>
                    </div>
                </div>
            </form>

        </div>
    </div>
{% endblock %}