backend/urls.py
# -*- coding: utf-8 -*-
#!/usr/bin/env python
#
# Copyright (c) 2010-2014 Mariusz Smenzyk <mariusz.smenzyk@sizeof.pl>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
"""

@author: Mariusz Smenzyk
@license: MIT License
@contact: mariusz.smenzyk@sizeof.pl
"""
from django.conf.urls import *
from rebateceo.urls import urlpatterns as rebateceo_urls


# Custom urls
urlpatterns = patterns('',
    # ...
) + rebateceo_urls

rebateceo/contrib/api/urls.py
# -*- coding: utf-8 -*-
#!/usr/bin/env python
#
# Copyright (c) 2010-2014 Mariusz Smenzyk <mariusz.smenzyk@sizeof.pl>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
"""

@author: Mariusz Smenzyk
@license: MIT License
@contact: mariusz.smenzyk@sizeof.pl
"""
from django.conf.urls import patterns, url, include
from . import views


urlpatterns = patterns('',
    #  Generic
    url(r'^content-type/list/', views.ContentTypeListView.as_view(), name='contenttype-list'),
    url(r'^info/', views.InfoView.as_view(), name='info'),
    url(r'^ping/', views.PingView.as_view(), name='ping'),
    url(r'^code/list/', views.CodeListView.as_view(), name='code-list'),

    #  Endpoints
    url(r'^map/', include('rebateceo.contrib.map.api.urls', namespace='map')),
    url(r'^tags/', include('rebateceo.contrib.tags.api.urls', namespace='tags')),
    url(r'^shop/', include('rebateceo.contrib.shop.api.urls', namespace='shop')),
    url(r'^trans/', include('rebateceo.contrib.trans.api.urls', namespace='trans')),
    url(r'^stand/', include('rebateceo.contrib.stand.api.urls', namespace='stand')),
    url(r'^nameday/', include('rebateceo.contrib.nameday.api.urls', namespace='nameday')),
    url(r'^mall/', include('rebateceo.contrib.mall.api.urls', namespace='mall')),
    url(r'^advert/', include('rebateceo.contrib.advert.api.urls', namespace='advert')),
    url(r'^contest/', include('rebateceo.contrib.contest.api.urls', namespace='contest')),
    url(r'^contest/bonarka1/', include('rebateceo.contrib.bonarka1.api.urls', namespace='bonarka1')),
    url(r'^backup/', include('rebateceo.contrib.backup.api.urls', namespace='backup')),
    url(r'^news/', include('rebateceo.contrib.news.api.urls', namespace='news')),
    url(r'^promotion/', include('rebateceo.contrib.promotion.api.urls', namespace='promotion')),
    url(r'^purchase/', include('rebateceo.contrib.purchase.api.urls', namespace='purchase')),
    url(r'^receipt/', include('rebateceo.contrib.purchase.api.urls', namespace='receipt')),  # alias
    url(r'^rebate/', include('rebateceo.contrib.rebate.api.urls', namespace='rebate')),
    url(r'^bookmark/', include('rebateceo.contrib.bookmark.api.urls', namespace='bookmark')),
    url(r'^profile/', include('rebateceo.contrib.profile.api.urls', namespace='profile')),
    url(r'^screensaver/', include('rebateceo.contrib.screensaver.api.urls', namespace='screensaver')),
    url(r'^tracking/', include('rebateceo.contrib.tracking.api.urls', namespace='tracking')),
    url(r'^campaign/', include('rebateceo.contrib.campaign.api.urls', namespace='campaign')),
    url(r'^card/', include('rebateceo.contrib.card.api.urls', namespace='card')),
    url(r'^verifier/', include('rebateceo.contrib.verifier.api.urls', namespace='verifier')),
    url(r'^loyalty/', include('rebateceo.contrib.loyalty.api.urls', namespace='loyalty')),
    url(r'^cache/', include('rebateceo.contrib.cache.api.urls', namespace='cache')),

    # url(r'^selfkiosk/', include('rebateceo.contrib.selfkiosk.api.urls', namespace='selfkiosk')),
    # url(r'^lottery/', include('rebateceo.contrib.lottery.api.urls', namespace='lottery')),
    # url(r'^lottery-v2/', include('rebateceo.contrib.lottery_v2.api.urls', namespace='lottery-v2')),
    # url(r'^lottery-v3/', include('rebateceo.contrib.lottery_v3.api.urls', namespace='lottery-v3')),
    # url(r'^lottery-v4/', include('rebateceo.contrib.lottery_v4.api.urls', namespace='lottery-v4')),
    # url(r'^printlog/', include('rebateceo.contrib.printlog.api.urls', namespace='printlog')),
    # url(r'^adv/', include('rebateceo.contrib.adv.api.urls', namespace='adv')),

    # url(r'^backup/', BackupView.as_view(), name='backup'),
)

rebateceo/contrib/bookmark/urls.py
# -*- coding: utf-8 -*-
#!/usr/bin/env python
#
# Copyright (c) 2010-2014 Mariusz Smenzyk <mariusz.smenzyk@sizeof.pl>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
"""

@author: Mariusz Smenzyk
@license: MIT License
@contact: mariusz.smenzyk@sizeof.pl
"""

try:
    from django.conf.urls.defaults import patterns, url
except ImportError:
    from django.conf.urls import patterns, url

from .views import BookmarksListView

urlpatterns = patterns('rebateceo.contrib.bookmark.views',
    url(r'^bookmark/$', 'bookmark', name='bookmark'),
    url(r'^bookmark$', BookmarksListView.as_view(), name='bookmark'),
    url(r'^ajax_form/$', 'ajax_form', name='ajax_form'),
)

rebateceo/contrib/verifier/urls.py
# -*- coding: utf-8 -*-
#!/usr/bin/env python
#
# Copyright (c) 2010-2014 Mariusz Smenzyk <mariusz.smenzyk@sizeof.pl>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
"""

@author: Mariusz Smenzyk
@license: MIT License
@contact: mariusz.smenzyk@sizeof.pl
"""
from django.conf.urls import patterns, url
from . import views


urlpatterns = patterns('',
    url(r'^list/$', views.VerifierListView.as_view(), name='list'),
    url(r'^create/$', views.VerifierCreateView.as_view(), name='create'),
    url(r'^update/(?P<pk>[0-9]+)/$', views.VerifierUpdateView.as_view(), name='update'),
    url(r'^delete/(?P<pk>[0-9]+)/$', views.VerifierDeleteView.as_view(), name='delete'),
)

rebateceo/urls.py
# -*- coding: utf-8 -*-
#!/usr/bin/env python
#
# Copyright (c) 2010-2014 Mariusz Smenzyk <mariusz.smenzyk@sizeof.pl>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
"""

@author: Mariusz Smenzyk
@license: MIT License
@contact: mariusz.smenzyk@sizeof.pl
"""
from django.conf.urls import *
from django.conf import settings
from django.contrib import admin

admin.autodiscover()


urlpatterns = patterns('',
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^tinymce/', include('tinymce.urls')),

    # Project urls
    # url(r'^map/', include('rebateceo.contrib.map.urls', namespace='map')),
    # url(r'^demo/', include('rebateceo.contrib.demo.urls')),
    # url(r'^manager/', include('rebateceo.contrib.manager.urls', namespace='manager')),
    # url(r'^operator/', include('rebateceo.contrib.operator.urls', namespace='operator')),
    # url(r'^account/', include('rebateceo.contrib.account.urls')),
    # url(r'^rebate/', include('rebateceo.contrib.rebate.urls', namespace='rebate')),

    # url(r'^shops/', include('rebateceo.contrib.shop.urls', namespace='shop')),
    # url(r'^sms/', include('rebateceo.contrib.sms.urls', namespace='sms')),
    # url(r'^report/', include('rebateceo.contrib.report.urls', namespace='report')),
    # url(r'^purchase/', include('rebateceo.contrib.purchase.urls', namespace='purchase')),
    # url(r'^receipt/', include('rebateceo.contrib.receipt.urls', namespace='receipt')),
    # url(r'^campaigns/', include('rebateceo.contrib.campaigns.urls', namespace='campaigns')),
    # url(r'^qrcode/', include('rebateceo.contrib.urls', namespace='qrcode')),
    url(r'^tags/', include('rebateceo.contrib.tags.urls', namespace='tags')),
    url(r'^websocket/', include('rebateceo.contrib.websocket.urls', namespace='websocket')),
    url(r'^tracking/', include('rebateceo.contrib.tracking.urls', namespace='tracking')),
    url(r'^account/', include('userena.urls')),
    url(r'^messages/', include('userena.contrib.umessages.urls')),
    url(r'^api/', include('rebateceo.contrib.api.urls', namespace='api')),
    url(r'^api/auth/', include('rebateceo.contrib.authorize.api.urls', namespace='auth')),
    url(r'^api/docs/', include('rest_framework_swagger.urls')),
    url(r'^crossdomain.xml$', 'rebateceo.crossdomain.xml', name='crossdomain'),
    url(r'^$', include('rebateceo.contrib.dashboard.urls', namespace='dashboard')),
    url(r'^cache/', include('rebateceo.contrib.cache.urls', namespace='cache')),
    url(r'^promotions/', include('rebateceo.contrib.promotion.urls', namespace='promotions')),
    )


if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve',
         {'document_root': settings.MEDIA_ROOT}),
        (r'^static/(?P<path>.*)$', 'django.views.static.serve',
         {'document_root': settings.STATIC_ROOT}),
    )

rebateceo/contrib/verifier/api/views/adv.py
# -*- coding: utf-8 -*-
# !/usr/bin/env python
#
# Copyright (c) 2010-2014 Mariusz Smenzyk <mariusz.smenzyk@sizeof.pl>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
"""

@author: Mariusz Smenzyk
@license: MIT License
@contact: mariusz.smenzyk@sizeof.pl
"""
from rest_framework.generics import ListAPIView
from ... import models
from ..bases import VerifierBaseAPIView
from .. import serializers


class AdvListView(VerifierBaseAPIView, ListAPIView):
    # authentication_classes = (TokenAuthentication,)
    # permission_classes = (IsAuthenticated,)
    serializer_class = serializers.AdvSerializer
    queryset = models.Adv.objects.all()

    def filter_queryset(self, qs):
        return qs.filter(shop__verifiers__in=[self.verifier])

rebateceo/contrib/verifier/api/views/config.py
# -*- coding: utf-8 -*-
# !/usr/bin/env python
#
# Copyright (c) 2010-2014 Mariusz Smenzyk <mariusz.smenzyk@sizeof.pl>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
"""

@author: Mariusz Smenzyk
@license: MIT License
@contact: mariusz.smenzyk@sizeof.pl
"""
from constance import config
from django.conf import settings
from rest_framework.generics import GenericAPIView, RetrieveAPIView
from rest_framework.response import Response
from django.utils.translation import ugettext as _
from .. import bases, serializers


class ConfigView(GenericAPIView):

    def get_config(self, request, *args, **kwargs):
        varifier_config, prefix = {}, 'verifier_'
        for field in settings.CONSTANCE_CONFIG:
            varifier_config.update({field.lower().replace(prefix, ''): getattr(config, field)})
        return {
            'config': {
                'description': _('This are defaults settings for all verifiers!'),
                'verifier': varifier_config
            }
        }

    def get(self, request, *args, **kwargs):
        return Response(self.get_config(request, *args, **kwargs))


class VerifierConfigView(bases.VerifierBaseAPIView, RetrieveAPIView):
    serializer_class = serializers.VerifierSerializer

rebateceo/contrib/verifier/templates/verifier/base.html
{% extends "base.html" %}
{% load i18n %}

{% block page-header-title %}
{% trans "Verifiers" %}
{% endblock %}

rebateceo/contrib/verifier/templates/verifier/create.html
{% extends "verifier/update.html" %}
{% load i18n %}
{% load bootstrap3 %}

{% block page-header-title %}
{% trans "Add new device" %}
{% endblock %}

rebateceo/contrib/verifier/templates/verifier/delete.html
{% extends "verifier/base.html" %}
{% load i18n %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <h2>{% trans "Are you sure, that you want to delete this record?" %}</h2>
        <form class="form-horizontal" role="form" method="post" action="">
            {% csrf_token %}
            <div class="form-actions fluid">
                <div class="col-md-offset-3 col-md-9">
                    <button type="submit" class="btn red">{% trans "Delete" %}</button>
                    <a href="{% url 'verifier:list' %}" class="btn default">{% trans "Cancel" %}</a>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

rebateceo/contrib/verifier/templates/verifier/list.html
{% extends "verifier/base.html" %}
{% load i18n %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <!-- BEGIN SAMPLE TABLE PORTLET-->
        <div class="portlet">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-gift"></i>{% trans "Verifiers" %}
                </div>
                <div class="tools">
                    <a href="javascript:;" class="collapse">
                    </a>
                    <!--<a href="#portlet-config" data-toggle="modal" class="config">-->
                    <!--</a>-->
                    <!--<a href="javascript:;" class="reload">-->
                    <!--</a>-->
                    <!--<a href="javascript:;" class="remove">-->
                    <!--</a>-->
                </div>
            </div>
            <div class="portlet-body">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-advance table-hover">
                        <thead>
                        <tr>
                            <th>
                                <i class="fa fa-briefcase"></i> {% trans "Shop" %}
                            </th>
                            <th class="hidden-xs">
                                <i class="fa fa-user"></i> {% trans "Imei" %}
                            </th>
                            <th>
                            </th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for verifier in object_list %}
                        <tr>
                            <td class="highlight">
                                <div class="success">
                                </div>
                                <a href="{% url 'admin:verifier_verifier_change' verifier.pk %}">
                                    {{ verifier.shop }}</a>
                            </td>
                            <td class="hidden-xs">
                                {{ verifier.imei }}
                            </td>
                            <td>
                                <a href="{% url 'admin:verifier_verifier_change' verifier.pk %}"
                                   class="btn default btn-xs purple"><i class="fa fa-edit"></i> {% trans "Edit" %} </a>
                                <a href="{% url 'admin:verifier_verifier_delete' verifier.pk %}"
                                   class="btn default btn-xs black"> <i class="fa fa-trash-o"></i> {% trans "Delete" %}
                                </a>
                            </td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <!-- END SAMPLE TABLE PORTLET-->
    </div>
</div>
{% endblock %}

rebateceo/contrib/verifier/templates/verifier/update.html
{% extends "verifier/base.html" %}
{% load bootstrap3 %}
{% load i18n %}


{% block page-header-title %}
Edit <i>{{ object }}</i>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <form class="" role="form" method="post" action="">
            {% csrf_token %}
            <div class="form-body">
                {% bootstrap_form form %}
            </div>
            <div class="form-actions fluid">
                <div class="col-md-offset-3 col-md-9">
                    <button type="submit" class="btn red">{% trans "Save" %}</button>
                    <a href="{% url 'verifier:list' %}" class="btn default">{% trans "Cancel" %}</a>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}